### ISSUE TITLE
could not create new container while Docker > v1.10

### ISSUE THREAD

**Issue by qxhy123** [codetainerapp/codetainer#31]
error says:
Codetainer 19:41:28 [FATAL] Unable to create codetainer: API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}

**Comment by tjomk** [comment]
This should be solved when https://github.com/codetainerapp/codetainer/pull/33 gets merged.

Meanwhile you can bump the version yourself

**Comment by djcas9** [comment]
@tjomk @qxhy123 merged
